import { Solution, SolutionCategory, SolutionStats } from '@/types/solutions'

const SOLUTIONS_DATA: Solution[] = [
  // === NĂNG LƯỢNG TÁI TẠO ===
  {
    id: 're-01',
    title: 'Nhà máy điện mặt trời Ninh Thuận',
    description: 'Cụm nhà máy điện mặt trời lớn nhất Đông Nam Á tại Ninh Thuận với công suất 450MW, cung cấp điện sạch cho hơn 200,000 hộ gia đình.',
    category: 'renewable-energy',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    impact: 'Giảm 520,000 tấn CO2/năm',
    scale: 'national',
    status: 'active',
    link: 'https://www.evn.com.vn',
    year: 2020,
    esgAlignment: ['environment'],
    standards: [{ type: 'iso-37122', domains: ['energy', 'environment'] }],
  },
  {
    id: 're-02',
    title: 'Điện gió ngoài khơi Hornsea (UK)',
    description: 'Trang trại gió ngoài khơi lớn nhất thế giới với công suất 2.8GW, đủ cung cấp điện cho 2.5 triệu hộ gia đình tại Anh.',
    category: 'renewable-energy',
    country: 'Vương quốc Anh',
    region: 'Châu Âu',
    impact: 'Cung cấp điện cho 2.5 triệu hộ',
    scale: 'national',
    status: 'active',
    link: 'https://hornseaprojects.co.uk',
    year: 2022,
    esgAlignment: ['environment', 'social'],
  },
  {
    id: 're-03',
    title: 'Hydrogen xanh Pilbara (Úc)',
    description: 'Dự án sản xuất hydrogen xanh từ năng lượng mặt trời quy mô 26GW tại Tây Úc, xuất khẩu nhiên liệu sạch sang châu Á.',
    category: 'renewable-energy',
    country: 'Úc',
    region: 'Châu Đại Dương',
    impact: 'Sản xuất 3.5 triệu tấn H2/năm',
    scale: 'global',
    status: 'planned',
    link: 'https://asianrehub.com',
    year: 2028,
    esgAlignment: ['environment', 'governance'],
  },
  {
    id: 're-04',
    title: 'Điện gió Bạc Liêu (Việt Nam)',
    description: 'Dự án điện gió ven biển Bạc Liêu với 62 tua-bin, công suất 99.2MW, mở đường cho ngành năng lượng gió Việt Nam.',
    category: 'renewable-energy',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    impact: 'Giảm 150,000 tấn CO2/năm',
    scale: 'national',
    status: 'active',
    link: 'https://www.evn.com.vn',
    year: 2021,
    esgAlignment: ['environment'],
    standards: [{ type: 'iso-37122', domains: ['energy'] }],
  },
  {
    id: 're-05',
    title: 'ITER - Lò phản ứng nhiệt hạch (Pháp)',
    description: 'Dự án quốc tế xây dựng lò phản ứng nhiệt hạch thử nghiệm, hứa hẹn nguồn năng lượng vô tận và sạch cho tương lai.',
    category: 'renewable-energy',
    country: 'Pháp (Quốc tế)',
    region: 'Châu Âu',
    impact: 'Năng lượng vô tận, không phát thải',
    scale: 'global',
    status: 'planned',
    link: 'https://www.iter.org',
    year: 2035,
    esgAlignment: ['environment', 'governance'],
  },
  {
    id: 're-06',
    title: 'Nhà máy thủy điện nổi (Hàn Quốc)',
    description: 'Hệ thống pin mặt trời nổi trên hồ chứa thủy điện Hapcheon, kết hợp thủy điện và năng lượng mặt trời, tiết kiệm đất.',
    category: 'renewable-energy',
    country: 'Hàn Quốc',
    region: 'Đông Á',
    impact: 'Tiết kiệm 30% diện tích đất',
    scale: 'national',
    status: 'active',
    link: 'https://www.kepco.co.kr',
    year: 2023,
    esgAlignment: ['environment'],
  },
  {
    id: 're-07',
    title: 'Noor Ouarzazate (Morocco)',
    description: 'Tổ hợp năng lượng mặt trời tập trung lớn nhất thế giới tại sa mạc Sahara, công suất 580MW với khả năng lưu trữ nhiệt.',
    category: 'renewable-energy',
    country: 'Morocco',
    region: 'Châu Phi',
    impact: 'Cung cấp điện cho 2 triệu người',
    scale: 'national',
    status: 'active',
    link: 'https://www.masen.ma',
    year: 2020,
    esgAlignment: ['environment', 'social'],
  },

  // === GIAO THÔNG XANH ===
  {
    id: 'gt-01',
    title: 'Metro TP. Hồ Chí Minh Tuyến 1',
    description: 'Tuyến metro đầu tiên của Việt Nam (Bến Thành - Suối Tiên), dài 19.7km, giảm tắc nghẽn và ô nhiễm giao thông đô thị.',
    category: 'green-transport',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    impact: 'Vận chuyển 620,000 hành khách/ngày',
    scale: 'local',
    status: 'active',
    link: 'https://www.hcmc-metro.com',
    year: 2024,
    esgAlignment: ['environment', 'social'],
    standards: [{ type: 'iso-37122', domains: ['transportation'] }],
  },
  {
    id: 'gt-02',
    title: 'Xe buýt điện VinBus (Việt Nam)',
    description: 'Hệ thống xe buýt điện VinBus hoạt động tại Hà Nội và TP.HCM, đội xe 200+ chiếc, không phát thải trực tiếp.',
    category: 'green-transport',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    impact: 'Giảm 6,000 tấn CO2/năm',
    scale: 'national',
    status: 'active',
    link: 'https://vinbus.vn',
    year: 2022,
    esgAlignment: ['environment', 'social'],
    standards: [{ type: 'iso-37122', domains: ['transportation', 'environment'] }],
  },
  {
    id: 'gt-03',
    title: 'Xe buýt điện Thâm Quyến (Trung Quốc)',
    description: 'Thành phố đầu tiên trên thế giới điện hóa 100% hệ thống xe buýt công cộng với 16,000+ xe buýt điện.',
    category: 'green-transport',
    country: 'Trung Quốc',
    region: 'Đông Á',
    impact: 'Giảm 1.35 triệu tấn CO2/năm',
    scale: 'local',
    status: 'completed',
    year: 2018,
    esgAlignment: ['environment', 'social', 'governance'],
  },
  {
    id: 'gt-04',
    title: 'Hạ tầng xe đạp Amsterdam',
    description: 'Mạng lưới 767km đường xe đạp chuyên dụng, chiếm 38% phương tiện di chuyển toàn thành phố, mô hình toàn cầu.',
    category: 'green-transport',
    country: 'Hà Lan',
    region: 'Châu Âu',
    impact: '38% di chuyển bằng xe đạp',
    scale: 'local',
    status: 'active',
    year: 2023,
    esgAlignment: ['environment', 'social'],
  },
  {
    id: 'gt-05',
    title: 'Shinkansen tốc độ cao (Nhật Bản)',
    description: 'Hệ thống tàu cao tốc phát thải CO2 thấp hơn 8 lần so với máy bay, vận chuyển 420,000 hành khách/ngày.',
    category: 'green-transport',
    country: 'Nhật Bản',
    region: 'Đông Á',
    impact: 'Thấp hơn 8x CO2 so với bay',
    scale: 'national',
    status: 'active',
    year: 1964,
    esgAlignment: ['environment', 'social'],
  },
  {
    id: 'gt-06',
    title: 'Phà điện E-Ferry Ellen (Đan Mạch)',
    description: 'Phà điện hoàn toàn chạy bằng pin lớn nhất thế giới, chứng minh khả năng vận tải biển không phát thải.',
    category: 'green-transport',
    country: 'Đan Mạch',
    region: 'Châu Âu',
    impact: 'Giảm 2,000 tấn CO2/năm',
    scale: 'local',
    status: 'active',
    link: 'https://www.e-ferry.eu',
    year: 2019,
    esgAlignment: ['environment'],
  },
  {
    id: 'gt-07',
    title: 'Hyperloop (UAE - Ấn Độ)',
    description: 'Dự án hệ thống vận chuyển siêu tốc Hyperloop kết nối Mumbai-Pune (150km trong 25 phút), giảm thời gian di chuyển 80%.',
    category: 'green-transport',
    country: 'Ấn Độ',
    region: 'Nam Á',
    impact: 'Giảm 80% thời gian di chuyển',
    scale: 'national',
    status: 'planned',
    year: 2030,
    esgAlignment: ['environment', 'social'],
  },

  // === NÔNG NGHIỆP BỀN VỮNG ===
  {
    id: 'na-01',
    title: 'Lúa giảm phát thải mê-tan (Việt Nam)',
    description: 'Chương trình canh tác lúa AWD (ngập khô xen kẽ) tại đồng bằng sông Cửu Long, giảm 30-50% khí mê-tan.',
    category: 'sustainable-agriculture',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    impact: 'Giảm 30-50% phát thải CH4',
    scale: 'national',
    status: 'active',
    year: 2021,
    esgAlignment: ['environment', 'social'],
  },
  {
    id: 'na-02',
    title: 'Vertical Farming Sky Greens (Singapore)',
    description: 'Trang trại dọc sử dụng 5% nước và 1/10 diện tích so với nông nghiệp truyền thống, sản xuất rau xanh trong đô thị.',
    category: 'sustainable-agriculture',
    country: 'Singapore',
    region: 'Đông Nam Á',
    impact: 'Tiết kiệm 95% nước tưới',
    scale: 'local',
    status: 'active',
    link: 'https://www.skygreens.com',
    year: 2012,
    esgAlignment: ['environment', 'social'],
  },
  {
    id: 'na-03',
    title: 'Nông nghiệp hữu cơ EU Green Deal',
    description: 'Chiến lược Farm to Fork của EU: 25% diện tích nông nghiệp chuyển sang hữu cơ trước 2030, giảm 50% thuốc trừ sâu.',
    category: 'sustainable-agriculture',
    country: 'EU',
    region: 'Châu Âu',
    impact: 'Giảm 50% thuốc trừ sâu',
    scale: 'global',
    status: 'active',
    link: 'https://ec.europa.eu/food/farm2fork_en',
    year: 2020,
    esgAlignment: ['environment', 'governance'],
  },
  {
    id: 'na-04',
    title: 'Tưới nhỏ giọt Netafim (Israel)',
    description: 'Công nghệ tưới nhỏ giọt tiên phong từ Israel, áp dụng tại 110+ quốc gia, tiết kiệm 60% nước so với tưới truyền thống.',
    category: 'sustainable-agriculture',
    country: 'Israel',
    region: 'Trung Đông',
    impact: 'Tiết kiệm 60% nước tưới',
    scale: 'global',
    status: 'active',
    link: 'https://www.netafim.com',
    year: 1965,
    esgAlignment: ['environment'],
  },
  {
    id: 'na-05',
    title: 'Cà phê bền vững Đắk Lắk (Việt Nam)',
    description: 'Chương trình VnSAT hỗ trợ 100,000 hộ nông dân trồng cà phê bền vững, giảm phân bón hóa học 30%, tăng thu nhập 20%.',
    category: 'sustainable-agriculture',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    impact: 'Giảm 30% phân bón hóa học',
    scale: 'national',
    status: 'active',
    year: 2015,
    esgAlignment: ['environment', 'social'],
  },
  {
    id: 'na-06',
    title: 'Trồng rừng ngập mặn (Bangladesh)',
    description: 'Chương trình trồng 2 triệu hecta rừng ngập mặn bảo vệ bờ biển, hấp thụ CO2, tạo sinh kế cho 500,000 gia đình.',
    category: 'sustainable-agriculture',
    country: 'Bangladesh',
    region: 'Nam Á',
    impact: 'Bảo vệ 500,000 gia đình ven biển',
    scale: 'national',
    status: 'active',
    year: 2019,
    esgAlignment: ['environment', 'social'],
  },
  {
    id: 'na-07',
    title: 'Nông nghiệp chính xác AI (Mỹ)',
    description: 'Ứng dụng AI và drone trong nông nghiệp chính xác, tối ưu phân bón/thuốc BVTV theo từng m², giảm 40% đầu vào.',
    category: 'sustainable-agriculture',
    country: 'Mỹ',
    region: 'Bắc Mỹ',
    impact: 'Giảm 40% đầu vào nông nghiệp',
    scale: 'global',
    status: 'active',
    year: 2022,
    esgAlignment: ['environment', 'governance'],
  },

  // === QUẢN LÝ RÁC THẢI ===
  {
    id: 'wm-01',
    title: 'Kinh tế tuần hoàn Thụy Điển',
    description: 'Thụy Điển tái chế 99% rác thải sinh hoạt. Nhập khẩu rác từ nước ngoài để đốt phát điện. Mô hình kinh tế tuần hoàn hàng đầu.',
    category: 'waste-management',
    country: 'Thụy Điển',
    region: 'Châu Âu',
    impact: 'Tái chế 99% rác thải',
    scale: 'national',
    status: 'active',
    year: 2020,
    esgAlignment: ['environment', 'governance'],
  },
  {
    id: 'wm-02',
    title: 'Ocean Cleanup - Dọn rác đại dương',
    description: 'Dự án sáng tạo của Boyan Slat, dùng hệ thống nổi thu gom rác nhựa Great Pacific Garbage Patch. Đã thu 200+ tấn.',
    category: 'waste-management',
    country: 'Hà Lan',
    region: 'Toàn cầu',
    impact: 'Thu gom 200+ tấn nhựa đại dương',
    scale: 'global',
    status: 'active',
    link: 'https://theoceancleanup.com',
    year: 2018,
    esgAlignment: ['environment'],
  },
  {
    id: 'wm-03',
    title: 'Xử lý rác thải điện tử (Nhật Bản)',
    description: 'Chương trình thu hồi kim loại quý từ thiết bị điện tử cũ. Olympic Tokyo 2020 sử dụng huy chương từ điện thoại tái chế.',
    category: 'waste-management',
    country: 'Nhật Bản',
    region: 'Đông Á',
    impact: 'Thu hồi 78,985 tấn thiết bị cũ',
    scale: 'national',
    status: 'active',
    year: 2017,
    esgAlignment: ['environment', 'social'],
  },
  {
    id: 'wm-04',
    title: 'Phân loại rác tại nguồn TP.HCM',
    description: 'Chương trình phân loại rác tại nguồn cho 10 triệu dân, mục tiêu giảm 50% rác thải chôn lấp trước 2030.',
    category: 'waste-management',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    impact: 'Giảm 50% rác chôn lấp (mục tiêu)',
    scale: 'local',
    status: 'active',
    year: 2023,
    esgAlignment: ['environment', 'social', 'governance'],
    standards: [{ type: 'iso-37122', domains: ['solid-waste', 'environment'] }],
  },
  {
    id: 'wm-05',
    title: 'Biogas từ rác thải nông nghiệp (Ấn Độ)',
    description: 'Chương trình GOBARDHAN chuyển đổi phân gia súc và rác nông nghiệp thành khí biogas cho 500+ làng, thay thế nhiên liệu hóa thạch.',
    category: 'waste-management',
    country: 'Ấn Độ',
    region: 'Nam Á',
    impact: 'Cung cấp năng lượng cho 500+ làng',
    scale: 'national',
    status: 'active',
    year: 2021,
    esgAlignment: ['environment', 'social'],
  },
  {
    id: 'wm-06',
    title: 'Gạch nhựa tái chế (Kenya)',
    description: 'Nzambi Matee tạo gạch xây dựng từ nhựa tái chế, bền hơn bê tông 5-7 lần, xử lý 20 tấn nhựa/ngày.',
    category: 'waste-management',
    country: 'Kenya',
    region: 'Châu Phi',
    impact: 'Xử lý 20 tấn nhựa/ngày',
    scale: 'local',
    status: 'active',
    link: 'https://gjenge.co.ke',
    year: 2020,
    esgAlignment: ['environment', 'social'],
  },
  {
    id: 'wm-07',
    title: 'Hệ thống ủ phân compost Hàn Quốc',
    description: 'Chính sách bắt buộc phân loại rác thực phẩm toàn quốc từ 2005, giảm 95% rác thực phẩm ra bãi chôn, chuyển thành phân bón/biogas.',
    category: 'waste-management',
    country: 'Hàn Quốc',
    region: 'Đông Á',
    impact: 'Giảm 95% rác thực phẩm chôn lấp',
    scale: 'national',
    status: 'completed',
    year: 2005,
    esgAlignment: ['environment', 'governance'],
  },

  // === ISO 37122 - SMART CITY BỀN VỮNG ===
  {
    id: 'iso-01',
    title: 'Smart Grid TP.HCM',
    description: 'Hệ thống lưới điện thông minh Smart Grid tại TP.HCM với AMI (Advanced Metering Infrastructure), tối ưu phân phối điện, giảm tổn thất truyền tải 15% và tích hợp nguồn năng lượng tái tạo phân tán.',
    category: 'renewable-energy',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    impact: 'Giảm 15% tổn thất truyền tải điện',
    scale: 'local',
    status: 'active',
    year: 2023,
    esgAlignment: ['environment', 'governance'],
    standards: [{ type: 'iso-37122', domains: ['energy', 'telecom-innovation'] }],
  },
  {
    id: 'iso-02',
    title: 'Hệ thống giao thông thông minh Singapore',
    description: 'Singapore triển khai ITS (Intelligent Transport System) toàn diện: ERP điện tử, xe buýt tự lái, ứng dụng MaaS (Mobility-as-a-Service), giảm tắc nghẽn 20% và thời gian di chuyển trung bình 15%.',
    category: 'green-transport',
    country: 'Singapore',
    region: 'Đông Nam Á',
    impact: 'Giảm 20% tắc nghẽn giao thông',
    scale: 'national',
    status: 'active',
    year: 2022,
    esgAlignment: ['environment', 'social', 'governance'],
    standards: [{ type: 'iso-37122', domains: ['transportation', 'telecom-innovation'] }],
  },
  {
    id: 'iso-03',
    title: 'Barcelona Superblocks',
    description: 'Mô hình quy hoạch đô thị Superblocks của Barcelona: nhóm 9 block thành "superblock" hạn chế xe hơi, tăng không gian xanh và đi bộ. Giảm ô nhiễm NO2 25%, tăng kinh doanh địa phương 30%.',
    category: 'green-transport',
    country: 'Tây Ban Nha',
    region: 'Châu Âu',
    impact: 'Giảm 25% ô nhiễm NO2',
    scale: 'local',
    status: 'active',
    year: 2016,
    esgAlignment: ['environment', 'social'],
    standards: [{ type: 'iso-37122', domains: ['urban-planning', 'transportation', 'environment'] }],
  },
  {
    id: 'iso-04',
    title: 'Copenhagen Carbon Neutral 2025',
    description: 'Copenhagen đặt mục tiêu thành phố trung hòa carbon đầu tiên thế giới: 100% điện gió, hệ thống sưởi khu vực, 75% di chuyển bằng xe đạp/công cộng/đi bộ, và công nghệ thu giữ carbon.',
    category: 'renewable-energy',
    country: 'Đan Mạch',
    region: 'Châu Âu',
    impact: 'Mục tiêu Net Zero carbon 2025',
    scale: 'local',
    status: 'active',
    year: 2012,
    esgAlignment: ['environment', 'governance'],
    standards: [{ type: 'iso-37122', domains: ['environment', 'energy', 'transportation'] }],
  },
  {
    id: 'iso-05',
    title: 'Seoul Digital Twin City',
    description: 'Seoul xây dựng bản sao số (Digital Twin) toàn thành phố: mô phỏng giao thông, năng lượng, thiên tai real-time. Hỗ trợ ra quyết định quản trị đô thị dựa trên dữ liệu với 1,000+ cảm biến IoT.',
    category: 'green-transport',
    country: 'Hàn Quốc',
    region: 'Đông Á',
    impact: 'Quản trị đô thị thông minh real-time',
    scale: 'local',
    status: 'active',
    year: 2023,
    esgAlignment: ['governance', 'environment'],
    standards: [{ type: 'iso-37122', domains: ['governance', 'telecom-innovation'] }],
  },
  {
    id: 'iso-06',
    title: 'Đà Nẵng Smart City',
    description: 'Đà Nẵng triển khai Smart City đa lĩnh vực: IOC (Intelligent Operations Center), camera AI giám sát giao thông, ứng dụng công dân số, quản lý môi trường thông minh. Mục tiêu thành phố thông minh ASEAN.',
    category: 'green-transport',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    impact: 'Trung tâm điều hành thông minh IOC',
    scale: 'local',
    status: 'active',
    year: 2021,
    esgAlignment: ['governance', 'environment', 'social'],
    standards: [{ type: 'iso-37122', domains: ['governance', 'telecom-innovation', 'transportation', 'environment'] }],
  },
  {
    id: 'iso-07',
    title: 'Amsterdam Smart City',
    description: 'Nền tảng Amsterdam Smart City kết nối 100+ dự án đổi mới: lưới điện thông minh, quản lý rác IoT, nền kinh tế dữ liệu mở, mobility sharing. Hợp tác công-tư-dân.',
    category: 'renewable-energy',
    country: 'Hà Lan',
    region: 'Châu Âu',
    impact: 'Kết nối 100+ dự án đổi mới đô thị',
    scale: 'local',
    status: 'active',
    link: 'https://amsterdamsmartcity.com',
    year: 2016,
    esgAlignment: ['governance', 'environment'],
    standards: [{ type: 'iso-37122', domains: ['telecom-innovation', 'governance', 'energy'] }],
  },

  // === BREEAM COMMUNITIES ===
  {
    id: 'br-01',
    title: 'One Central Park Sydney',
    description: 'Tòa nhà xanh biểu tượng Sydney với vườn treo dọc 1,200 cây xanh, hệ thống tái sử dụng nước thải, pin mặt trời tích hợp. Đạt chứng nhận BREEAM Outstanding.',
    category: 'renewable-energy',
    country: 'Úc',
    region: 'Châu Đại Dương',
    impact: 'Giảm 50% tiêu thụ năng lượng',
    scale: 'local',
    status: 'completed',
    year: 2014,
    esgAlignment: ['environment'],
    standards: [{ type: 'breeam', categories: ['RE'] }],
  },
  {
    id: 'br-02',
    title: 'Masdar City Abu Dhabi',
    description: 'Thành phố sinh thái zero-carbon, zero-waste tại UAE: 100% năng lượng tái tạo, xe tự lái PRT, kiến trúc khí hậu sa mạc thông minh, trụ sở IRENA. Đầu tư $22 tỷ.',
    category: 'renewable-energy',
    country: 'UAE',
    region: 'Trung Đông',
    impact: 'Thành phố zero-carbon đầu tiên',
    scale: 'local',
    status: 'active',
    link: 'https://masdar.ae',
    year: 2008,
    esgAlignment: ['environment', 'governance'],
    standards: [{ type: 'breeam', categories: ['RE', 'LE'] }],
  },
  {
    id: 'br-03',
    title: 'BedZED London',
    description: 'Beddington Zero Energy Development - khu dân cư không phát thải carbon đầu tiên tại UK. 100 căn hộ với cách nhiệt siêu hiệu quả, điện mặt trời, xe chia sẻ, vật liệu tái chế.',
    category: 'waste-management',
    country: 'Vương quốc Anh',
    region: 'Châu Âu',
    impact: 'Giảm 90% nhu cầu sưởi',
    scale: 'local',
    status: 'completed',
    year: 2002,
    esgAlignment: ['environment', 'social'],
    standards: [{ type: 'breeam', categories: ['RE', 'TM'] }],
  },
  {
    id: 'br-04',
    title: 'Songdo International Business District',
    description: 'Thành phố thông minh từ đầu tại Hàn Quốc: hệ thống khí nén thu gom rác tự động, kênh nước trung tâm, 40% diện tích cây xanh, smart building toàn bộ. Đầu tư $35 tỷ.',
    category: 'waste-management',
    country: 'Hàn Quốc',
    region: 'Đông Á',
    impact: '40% diện tích dành cho cây xanh',
    scale: 'local',
    status: 'active',
    year: 2009,
    esgAlignment: ['environment', 'social', 'governance'],
    standards: [{ type: 'breeam', categories: ['GO', 'SE'] }],
  },
  {
    id: 'br-05',
    title: 'Vinhomes Grand Park',
    description: 'Đại đô thị xanh Vinhomes Grand Park tại TP.HCM: công viên 36ha, hồ cảnh quan, trường học, bệnh viện, trung tâm thương mại tích hợp. Áp dụng tiêu chuẩn xanh quốc tế cho cộng đồng 50,000 cư dân.',
    category: 'sustainable-agriculture',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    impact: 'Cộng đồng xanh 50,000 cư dân',
    scale: 'local',
    status: 'active',
    link: 'https://vinhomes.vn',
    year: 2020,
    esgAlignment: ['social', 'environment'],
    standards: [{ type: 'breeam', categories: ['SE', 'LE'] }],
  },
  {
    id: 'br-06',
    title: "King's Cross Development London",
    description: 'Tái phát triển khu vực 27ha King\'s Cross: 50 tòa nhà mới, 20 đường phố, 10 quảng trường, Granary Square. Tích hợp giao thông công cộng, đi bộ, và không gian xanh. Chuẩn BREEAM Excellent.',
    category: 'green-transport',
    country: 'Vương quốc Anh',
    region: 'Châu Âu',
    impact: 'Tái sinh đô thị 27ha',
    scale: 'local',
    status: 'active',
    link: 'https://www.kingscross.co.uk',
    year: 2011,
    esgAlignment: ['social', 'environment', 'governance'],
    standards: [{ type: 'breeam', categories: ['TM', 'SE'] }],
  },
  {
    id: 'br-07',
    title: 'Ecopark Hưng Yên',
    description: 'Khu đô thị sinh thái Ecopark: 500ha với 70% cây xanh và mặt nước, trường học quốc tế, bệnh viện, không gian cộng đồng. Mô hình đô thị xanh tiêu biểu Việt Nam với 30,000 cư dân.',
    category: 'sustainable-agriculture',
    country: 'Việt Nam',
    region: 'Đông Nam Á',
    impact: '70% diện tích cây xanh & mặt nước',
    scale: 'local',
    status: 'active',
    link: 'https://ecopark.com.vn',
    year: 2012,
    esgAlignment: ['environment', 'social'],
    standards: [{ type: 'breeam', categories: ['LE', 'SE'] }],
  },
]

// === Helpers ===

export function getAllSolutions(): Solution[] {
  return SOLUTIONS_DATA
}

export function getSolutionsByCategory(category: SolutionCategory): Solution[] {
  return SOLUTIONS_DATA.filter(s => s.category === category)
}

export function getSolutionsByStandard(standardType: 'iso-37122' | 'breeam'): Solution[] {
  return SOLUTIONS_DATA.filter(s =>
    s.standards?.some(st => st.type === standardType)
  )
}

export function getSolutionStats(): SolutionStats {
  const stats: SolutionStats = {
    total: SOLUTIONS_DATA.length,
    byCategory: {
      'renewable-energy': 0,
      'green-transport': 0,
      'sustainable-agriculture': 0,
      'waste-management': 0,
    },
    byScale: { local: 0, national: 0, global: 0 },
    byStatus: { active: 0, planned: 0, completed: 0 },
  }

  SOLUTIONS_DATA.forEach(s => {
    stats.byCategory[s.category]++
    stats.byScale[s.scale]++
    stats.byStatus[s.status]++
  })

  return stats
}

export function getVietnamSolutions(): Solution[] {
  return SOLUTIONS_DATA.filter(s => s.country === 'Việt Nam')
}
