import { NextRequest, NextResponse } from 'next/server'
import { fetchAllNews } from '@/services/news'
import { generateAISummary, generateSolutionsSummary, resetAICaches } from '@/services/aiSummary'
import { resetNewsCache } from '@/services/news'

export const dynamic = 'force-dynamic'
export const maxDuration = 60 // Allow up to 60s for cron job

export async function GET(request: NextRequest) {
  // Verify CRON_SECRET for security
  const authHeader = request.headers.get('authorization')
  const cronSecret = process.env.CRON_SECRET

  if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
    console.warn('[Cron] Unauthorized access attempt')
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const startTime = Date.now()
  const results: Record<string, string> = {}

  try {
    // 1. Reset caches to force fresh data
    resetNewsCache()
    resetAICaches()
    results.cacheReset = 'ok'

    // 2. Fetch fresh news (bypass cache)
    const articles = await fetchAllNews()
    results.newsArticles = `${articles.length} articles fetched`

    // 3. Generate AI summary with Gemini (force regenerate)
    const aiSummary = await generateAISummary(articles)
    results.aiSummary = `Generated by ${aiSummary.generatedBy} - ${aiSummary.highlights?.length || 0} highlights`

    // 4. Generate solutions summary (force regenerate)
    const solutionsSummary = await generateSolutionsSummary(true)
    results.solutionsSummary = `Generated by ${solutionsSummary.generatedBy} - ${solutionsSummary.trends?.length || 0} trends`

    const duration = Date.now() - startTime

    console.log(`[Cron] Refresh completed in ${duration}ms`, results)

    return NextResponse.json({
      success: true,
      duration: `${duration}ms`,
      timestamp: new Date().toISOString(),
      timezone: 'UTC (cron runs at 23:00, 05:00, 11:00 UTC = 06:00, 12:00, 18:00 VN)',
      results,
    })
  } catch (error) {
    const duration = Date.now() - startTime
    console.error(`[Cron] Refresh failed after ${duration}ms:`, error)

    return NextResponse.json({
      success: false,
      duration: `${duration}ms`,
      timestamp: new Date().toISOString(),
      error: error instanceof Error ? error.message : 'Unknown error',
      partialResults: results,
    }, { status: 500 })
  }
}
